apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rasterserv
parameters:
  - name: IMAGE_TAG
    value: "latest"
  - name: IMAGE_REGISTRY
    value: image-registry.apps.silver.devops.gov.bc.ca
  - name: IMAGE_NAMESPACE
    value: e1e498-tools
  - name: SECRET_KEY_NAME
    required: true
    value: wps-global
  - name: HOST
    value: wps-dev-rasterserv.apps.silver.devops.gov.bc.ca

objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: rasterserv
      name: rasterserv
    spec:
      replicas: 2
      selector:
        app: rasterserv
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: rasterserv
            name: rasterserv
        spec:
          containers:
            - name: rasterserv
              image: ${IMAGE_REGISTRY}/${IMAGE_NAMESPACE}/wps-server-raster:${IMAGE_TAG}
              ports:
                - containerPort: 8000
                  protocol: TCP
              env:
                - name: OBJECT_STORE_SERVER
                  valueFrom:
                    secretKeyRef:
                      name: ${SECRET_KEY_NAME}
                      key: object-store-server
                - name: OBJECT_STORE_USER_ID
                  valueFrom:
                    secretKeyRef:
                      name: ${SECRET_KEY_NAME}
                      key: object-store-user-id
                - name: OBJECT_STORE_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: ${SECRET_KEY_NAME}
                      key: object-store-secret
                - name: OBJECT_STORE_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: ${SECRET_KEY_NAME}
                      key: object-store-bucket
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 5
                periodSeconds: 30
                successThreshold: 1
                tcpSocket:
                  port: 8000
                timeoutSeconds: 5
              readinessProbe:
                httpGet:
                  path: /ready
                  port: 8000
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 30
                successThreshold: 1
                timeoutSeconds: 5
              resources:
                requests:
                  cpu: "0"
                  memory: "0"
                limits:
                  cpu: "0"
                  memory: "0"
  - apiVersion: v1
    kind: Service
    metadata:
      name: rasterserv
      labels:
        app: rasterserv
        name: rasterserv
    spec:
      ports:
        - name: 8000-tcp
          protocol: TCP
          port: 80
          targetPort: 8000
      selector:
        name: rasterserv
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: rasterserv
      labels:
        app: rasterserv
        name: rasterserv
    spec:
      host: ${HOST}
      port:
        targetPort: 8000-tcp
      to:
        kind: Service
        name: rasterserv
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
